version: '3.7'
services:
  web:
    image: canaa-educacao-web:dev
    container_name: canaa-educacao-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}
      - REACT_APP_URL_TRAINING_API=${REACT_APP_URL_TRAINING_API}
